language: node_js
services:
  - docker
before_install:
install:
  - bash curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
script:
  - bash scripts/env_vars.sh
deploy:
  provider: script
  script: bash scripts/deploy.sh 
  on:
    branch: master
    
