apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-database
  namespace: yellowphone-interviewscheduler-fe
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-database
  namespace: yellowphone-interviewscheduler-fe
  labels:
    app: mysql-database
spec:
  containers:
  - name: mysql-database
    image: mysql
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-database
      subPath: db
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: yellowphonestoresdata
  volumes:
  - name: mysql-database
    persistentVolumeClaim:
      claimName: mysql-database
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-database
  namespace: yellowphone-interviewscheduler-fe
spec:
  ports:
  - name: tcp3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-database
  type: ClusterIP
