apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-database
  namespace: ${KUBECTL_NAMESPACE} 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-database
  namespace: ${KUBECTL_NAMESPACE}
  labels:
    app: mysql-database
spec:
  containers:
  - name: mysql-database
    ports:
    - containerPort: 3306
    image: mysql
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-database
      subPath: db
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: ${DATABASE_PASSWORD}
  volumes:
  - name: mysql-database
    persistentVolumeClaim:
      claimName: mysql-database
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-database
  namespace: ${KUBECTL_NAMESPACE}
spec:
  clusterIP: 10.43.246.125
  ports:
  - name: tcp3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-database
  type: LoadBalancer
